### ISSUE TITLE
Night light not working

### ISSUE THREAD

**Issue by s0alqasim1d** [SuperiorOS-Devices/official_devices#42]
Hi, first of all, thanks for these releases, they are very valuable.

I am using the latest release, the night light doesn't seem to be working. I captured an error log, here:
[2022-04-19-23-31-20-night-light.txt](https://github.com/SuperiorOS-Devices/official_devices/files/8517334/2022-04-19-23-31-20-night-light.txt)
```
04-19 23:30:49.941 E/StrictMode(10740): Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.quickstep.inputconsumers.OtherActivityInputConsumer@67a5f50 The API:ViewConfiguration needs a proper configuration. Use UI contexts such as an activity or a context created via createWindowContext(Display, int, Bundle) or  createConfigurationContext(Configuration) with a proper configuration.
04-19 23:30:49.941 E/StrictMode(10740): java.lang.IllegalAccessException: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.quickstep.inputconsumers.OtherActivityInputConsumer@67a5f50
04-19 23:30:49.941 E/StrictMode(10740): 	at android.os.StrictMode.assertConfigurationContext(StrictMode.java:2296)
04-19 23:30:49.941 E/StrictMode(10740): 	at android.view.ViewConfiguration.get(ViewConfiguration.java:521)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.quickstep.inputconsumers.OtherActivityInputConsumer.<init>(OtherActivityInputConsumer.java:173)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.createOtherActivityInputConsumer(TouchInteractionService.java:819)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.newBaseConsumer(TouchInteractionService.java:803)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.newConsumer(TouchInteractionService.java:708)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.onInputEvent(TouchInteractionService.java:599)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.$r8$lambda$QnySfMPM3HQvC_OREg1W70p37mY(Unknown Source:0)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService$$ExternalSyntheticLambda4.onInputEvent(Unknown Source:2)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.systemui.shared.system.InputChannelCompat$InputEventReceiver$1.onInputEvent(InputChannelCompat.java:74)
04-19 23:30:49.941 E/StrictMode(10740): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
04-19 23:30:49.941 E/StrictMode(10740): 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-19 23:30:49.941 E/StrictMode(10740): 	at android.os.MessageQueue.next(MessageQueue.java:335)
04-19 23:30:49.941 E/StrictMode(10740): 	at android.os.Looper.loopOnce(Looper.java:161)
04-19 23:30:49.941 E/StrictMode(10740): 	at android.os.Looper.loop(Looper.java:288)
04-19 23:30:49.941 E/StrictMode(10740): 	at android.app.ActivityThread.main(ActivityThread.java:7871)
04-19 23:30:49.941 E/StrictMode(10740): 	at java.lang.reflect.Method.invoke(Native Method)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
04-19 23:30:49.941 E/StrictMode(10740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
04-19 23:30:50.456 F/linker  (13935): CANNOT LINK EXECUTABLE "/system/vendor/bin/mm-pp-dpps": library "libtinyxml.so" not found: needed by main executable
04-19 23:30:51.210 E/SDM     (643): ColorManager::ApplyLinearColorTransform: Apply PCC for SetTransform FAILED 
04-19 23:30:51.210 E/SDM     (643): HWCDisplay::HandleColorModeTransform: Failed to set Color Transform Matrix
04-19 23:30:51.210 E/SDM     (643): HWCDisplay::SetColorTransform: failed for hint = 1
04-19 23:30:51.210 E/SDM     (643): HWCDisplayPrimary::SetColorTransform: failed for hint = 1
---
--- a lot of repetition of the above four lines, github says its too long so I removed most of them. The log is uploaded though if you really need it.
---
04-19 23:30:55.472 F/linker  (13948): CANNOT LINK EXECUTABLE "/system/vendor/bin/mm-pp-dpps": library "libtinyxml.so" not found: needed by main executable
04-19 23:30:55.576 E/StrictMode(10740): Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.quickstep.inputconsumers.OtherActivityInputConsumer@9ada8a1 The API:ViewConfiguration needs a proper configuration. Use UI contexts such as an activity or a context created via createWindowContext(Display, int, Bundle) or  createConfigurationContext(Configuration) with a proper configuration.
04-19 23:30:55.576 E/StrictMode(10740): java.lang.IllegalAccessException: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.quickstep.inputconsumers.OtherActivityInputConsumer@9ada8a1
04-19 23:30:55.576 E/StrictMode(10740): 	at android.os.StrictMode.assertConfigurationContext(StrictMode.java:2296)
04-19 23:30:55.576 E/StrictMode(10740): 	at android.view.ViewConfiguration.get(ViewConfiguration.java:521)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.quickstep.inputconsumers.OtherActivityInputConsumer.<init>(OtherActivityInputConsumer.java:173)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.createOtherActivityInputConsumer(TouchInteractionService.java:819)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.newBaseConsumer(TouchInteractionService.java:803)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.newConsumer(TouchInteractionService.java:708)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.onInputEvent(TouchInteractionService.java:599)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService.$r8$lambda$QnySfMPM3HQvC_OREg1W70p37mY(Unknown Source:0)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.quickstep.TouchInteractionService$$ExternalSyntheticLambda4.onInputEvent(Unknown Source:2)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.systemui.shared.system.InputChannelCompat$InputEventReceiver$1.onInputEvent(InputChannelCompat.java:74)
04-19 23:30:55.576 E/StrictMode(10740): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
04-19 23:30:55.576 E/StrictMode(10740): 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-19 23:30:55.576 E/StrictMode(10740): 	at android.os.MessageQueue.next(MessageQueue.java:335)
04-19 23:30:55.576 E/StrictMode(10740): 	at android.os.Looper.loopOnce(Looper.java:161)
04-19 23:30:55.576 E/StrictMode(10740): 	at android.os.Looper.loop(Looper.java:288)
04-19 23:30:55.576 E/StrictMode(10740): 	at android.app.ActivityThread.main(ActivityThread.java:7871)
04-19 23:30:55.576 E/StrictMode(10740): 	at java.lang.reflect.Method.invoke(Native Method)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
04-19 23:30:55.576 E/StrictMode(10740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
To capture it, I started the logging in error level only, then switched to the settings>night light and switched it on then moved the intensity slider around.

**Comment by Darkstar085** [comment]
U didn't mentioned device btw.. ig it is whyred.. 

Fixed btw build will b up by today evening..

**Comment by s0alqasim1d** [comment]
You're right it is whyred. Sorry I thought the repo was for whyred specifically since I jumped to issues from the github releases that only showed whyred builds.

Thanks for your hard work.

**Comment by Darkstar085** [comment]
Fixed 

Refer to - https://t.me/superior_os/1301
